### ISSUE TITLE
A word* from me!

### ISSUE THREAD

**Issue by loneicewolf** [0vercl0k/kdmp-parser-rs#3]
Hello! I stumbled upon this from the  https://infosec.exchange/@0vercl0k/112134537380085052 link you made, I thought it's fascinating, and since I dont know rust, I thought this is a nice project  to check out; so thanks for making this repo!

this can be closed, I always tell people what repo is "nice" because it's rare to get a 'thank you' when you do something good; :+1: keep up the nice work!

**Comment by 0vercl0k** [comment]
Cheers for the kind words 🙏🏽
